name: Unit Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'tests/**'
      - 'src/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: UTC
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/requirements-tests.txt
      - name: Install the development package itself
        run: |
          python -m pip install -e .
      - name: Run tests with pytest and generate coverage report
        run: pytest --cov=cr.nimble --cov-report=xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          verbose: true
