name: Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'src/**'
      - 'examples/**'
  pull_request:
    branches:
      - main


jobs:
  build:
    name: Sphinx Build and Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install system packages
      run: |
        sudo apt-get update -y
        sudo apt-get install pandoc libgl1-mesa-dev optipng
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
        pip install -r docs/requirements.txt
    - name: Install the package itself in development mode
      run: |
        pip install -e .
    - name: Debugging information
      run: |
        pandoc --version    
        echo "github.ref:" ${{github.ref}}
        echo "github.event_name:" ${{github.event_name}}
        echo "github.head_ref:" ${{github.head_ref}}
        echo "github.base_ref:" ${{github.base_ref}}
        set -x
        git rev-parse --abbrev-ref HEAD
        git branch
        git branch -a
        git remote -v
        python --version
        pip --version
        pip list --not-required
        pip list
    - uses: ammaraskar/sphinx-problem-matcher@master
    - name: Build Sphinx docs
      run: |
        cd docs
        make html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
